export const allTasks = [
  {
    taskHeading: "Mobile App",
    taskItem: "Prepare Figma File",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "Buy section",
    taskItem: "Purchase the food section at shoprite.",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "Taking over the world",
    taskItem: "Raise Hell for them",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "Finish watching this Anime",
    taskItem: "Have you met chairman hong",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "There is a strangeness",
    taskItem: "Dictatorship is the way niggas take over countries",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "Making Pluto habitable",
    taskItem: "Raise Hell for them",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "What is my name again",
    taskItem: "Have you met chairman hong",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
  {
    taskHeading: "Who am I to you?",
    taskItem: "Dictatorship is the way niggas take over countries",
    dateCreated: new Date().getDate(),
    inProgress: false,
    complete: false,
    selected: false,
  },
];
